# -*- coding: utf-8 -*-
"""Features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wrNk_4M4mSRDdAq4hXvmrQoaSom9-nEo
"""

import csv
   
from google.colab import drive
drive.mount ('/content/gdrive')

with open('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
  rows = csv.read()
  print(rows)

#F1 Char Repitition

#F2 word count
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        total_words = len(line.split())
        line_details.append("Line %d has %d words" % (total_lines, total_words))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#https://stackoverflow.com/questions/31370809/count-the-number-of-characters-in-every-word-of-every-line-of-a-file

#F3 Sentence Count

#F4 Word per Sentence Count

#F5 Digit Count
valid_chars = set("1234567890")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Digit" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F6 character count
def fileCount(ajbanaltrial):
    #counting variables
    d = {"lines":0, "words": 0, "lengths":[]}
    #file is opened and assigned a variable
    with open('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
        for line in csv:
            # split into words
            spl = line.split()
            # increase count for each line
            d["lines"] += 1
            # add length of split list which will give total words
            d["words"] += len(spl)
            # get the length of each word and sum
            d["lengths"].append(sum(len(word) for word in spl))
    return d

def main():
    fname = input('Enter the name of the file to be used: ')
    data = fileCount(fname)
    print ("There are {lines} lines in the file.".format(**data))
    # enumerate over the lengths, outputting char count for each line
    for ind, s in enumerate(data["lengths"], 1):
        print("Line: {} has {} characters.".format(ind, s))
main()

#F7 Alphabet Count
valid_chars = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Digit" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F8 Upper Case Word Count

#F9 Upper Case Count
valid_chars = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Upper Case" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F10 Special Character Count
valid_chars = set("#,./?;:'!@$%^&*()_-+=[]")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Special Character" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F11 Exclamation Point Count
valid_chars = set("!")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Exclamation Point" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F12 Punctuation Mark Count
valid_chars = set(",")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Punctuation Mark" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F12 Question Mark Count
valid_chars = set("?")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Question Mark" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F13 Punctuation Mark Count
valid_chars = set(",")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Punctuation Mark" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F14 Period Count
valid_chars = set(".")
total_lines = total_words = total_chars = 0
line_details = []

with open ('gdrive/My Drive/Colab Notebooks/ajbanaltrial.csv', encoding="utf8", errors='ignore') as csv:
      for line in csv:
        total_lines += 1
        line_char_count = len([char for char in line if char in valid_chars])
        line_details.append("Line %d has %d Period" % (total_lines, line_char_count))

print ("There are", total_lines, "lines in the file.")
for line in line_details:
    print (line)

#F15 Alphanumeric Word Count

#F16 Words Beginning with Capital Letter Count

#F17 Irregular Word Count (e.g WaLa AkOnG lOvElIfE)

#F18 Emoji Count

#F19 Shortcut Words Count